= CloudBees action: Scan with Aquasec

Use this action to scan container images with the Aquasec scanner. 
Detect and fix security threats to your container-based cloud applications.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `image-location`
| String
| Yes
| The container image location.

| `image-tag`
| String
| Yes
| The container image tag.

| `server-url`
| String
| Yes
| The Aquasec server URL.

| `username`
| String
| Yes
| The Aquasec username.

| `password`
| String
| Yes
| The Aquasec password.

| `scannercli-username`
| String
| Yes
| The Aquasec scannercli username.

| `scannercli-password`
| String
| Yes
| The Aquasec scannercli password.

|===

== Usage example

In your YAML file, add:

[source,yaml,role="default-expanded"]
----

      - name: Scan with Aquasec
        uses: cloudbees-io/aquasec-scan-container@v1
        with:
          image-location: "example.com/local/alpine"
          image-tag: "latest"
          server-url: "${{ vars.AQUASEC_SERVER_URL }}"
          username: "${{ vars.AQUASEC_USERNAME }}"
          password: "${{ secrets.AQUASEC_PASSWORD }}"
          scannercli-username: "${{ vars.AQUASEC_SCANNERCLI_USERNAME }}"
          scannercli-password: "${{ secrets.AQUASEC_SCANNERCLI_PASSWORD }}"
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
